apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-app-2-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            server_url: https://kubernetes.default.svc
  #          - environment: qa
  #            server_url: https://kubernetes-qa.example.com
  #          - environment: stage
  #            server_url: https://kubernetes-prod.example.com
  #          - environment: prod
  #            server_url: https://kubernetes-prod.example.com
  template:
    metadata:
      name: '{{environment}}-nginx-app-2'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/christoffer-nielsen-knightec/argocd-applications'
        targetRevision: kustomize
        path: 'nginx-app-2/overlays/{{environment}}'
      destination:
        server: '{{server_url}}'
      #        namespace: 'tf-flash-{{environment}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true